#!/usr/bin/env bash

#: exec_target = cli

## Initialize stack and site (full reset)
##
## Usage: fin init-site

# Abort if anything fails
set -e

/var/www/.docksal/commands/terminus install
/var/www/.docksal/commands/refresh
